[package]
name = "paradoxum/react-test-renderer"
description = "A React renderer that outputs a JSON-serializable tree, used for testing React Luau components."
version = "17.3.10"
license = "MIT"
authors = ["Paradoxum Games", "Roblox <no-reply@roblox.com>"]
realm = "shared"
registry = "https://github.com/paradoxum-games/wally-index"
repository = "https://github.com/paradoxum-games/react-luau"
private = false
exclude = [
	"rotriever.toml",
	".robloxrc",
	"src/**/__tests__",
	"src/**/__tests__/**",
	"src/**/__snapshots__",
	"src/**/__snapshots__/**",
	"src/**/*.spec.lua",
	"src/**/*.test.lua",
]

[dependencies]
LuauPolyfill = "jsdotlua/luau-polyfill@=1.2.7"
React = "paradoxum/react@=17.3.10"
ReactGlobals = "paradoxum/react-globals@=17.3.10"
ReactReconciler = "paradoxum/react-reconciler@=17.3.10"
Scheduler = "paradoxum/react-scheduler@=17.3.10"
Shared = "paradoxum/react-shared@=17.3.10"
