[package]
name = "paradoxum/react-shared"
description = "Internal shared utilities used across React Luau packages."
version = "17.3.10"
license = "MIT"
authors = ["Paradoxum Games", "Roblox <no-reply@roblox.com>"]
realm = "shared"
registry = "https://github.com/paradoxum-games/wally-index"
repository = "https://github.com/paradoxum-games/react-luau"
private = true
exclude = [
	"rotriever.toml",
	".robloxrc",
	"src/**/__tests__",
	"src/**/__tests__/**",
	"src/**/__snapshots__",
	"src/**/__snapshots__/**",
	"src/**/*.spec.lua",
	"src/**/*.test.lua",
]

[dependencies]
LuauPolyfill = "jsdotlua/luau-polyfill@=1.2.7"
SafeFlags = "roblox/safe-flags@=0.1.2"
ReactGlobals = "paradoxum/react-globals@=17.3.10"
