--!strict
-- Generated by bin/generate-wally-workspace.py; do not edit by hand.
local aliasTargets = {
	ReactNoop = "ReactNoopRenderer",
}

local sourceKeys = {
	TestRunner = "Src",
}

local workspace: Instance? = script.Parent
while workspace ~= nil and workspace.Name ~= "_Workspace" do
	workspace = workspace.Parent
end

if workspace == nil then
	error("Dependency proxy " .. script:GetFullName() .. " is outside _Workspace")
end

local targetName = aliasTargets[script.Name] or script.Name
local localWrapper = workspace:FindFirstChild(targetName)
local target: Instance?

if localWrapper ~= nil then
	local sourceName = sourceKeys[targetName] or targetName
	target = localWrapper:FindFirstChild(sourceName)
else
	local packageRoot = workspace.Parent
	if packageRoot ~= nil then
		target = packageRoot:FindFirstChild(targetName)
	end
end

if target == nil or not target:IsA("ModuleScript") then
	error("Dependency proxy " .. script:GetFullName() .. " cannot resolve " .. targetName)
end

return require(target)
